SELECT a.AUTHOR_ID, a.AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) as TOTAL_SALES
FROM BOOK_SALES bs
JOIN BOOK b
ON bs.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID 
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') like '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;