# SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID in (
#     SELECT ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID in 
#         (SELECT ID
#         FROM ECOLI_DATA
#         WHERE PARENT_ID IS NULL)
#     );

WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL 
    
    SELECT e.ID, e.PARENT_ID, GEN.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    INNER JOIN GEN ON e.PARENT_ID = GEN.ID
)

SELECT ID
FROM GEN
WHERE GENERATION = 3;