# WITH CNT AS (
#     SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
#     FROM ECOLI_DATA
#     GROUP BY PARENT_ID 
#     HAVING PARENT_ID IS NOT NULL
# )

# SELECT 
#     ID,
#     IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
# FROM ECOLI_DATA ED
# LEFT JOIN CNT
# ON CNT.PARENT_ID = ED.ID
# ORDER BY ID;

SELECT A.ID ID,
       COUNT(B.ID) CHILD_COUNT
FROM ECOLI_DATA A 
LEFT JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
GROUP BY ID
ORDER BY ID;