WITH BEST_REST AS (
    SELECT 
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM 
        REST_INFO
    GROUP BY 
        FOOD_TYPE
)

SELECT  
    RI.FOOD_TYPE, 
    RI.REST_ID, 
    RI.REST_NAME, 
    RI.FAVORITES
FROM 
    REST_INFO RI
JOIN 
    BEST_REST BR
ON 
    RI.FOOD_TYPE = BR.FOOD_TYPE AND RI.FAVORITES = BR.MAX_FAVORITES
ORDER BY 
    RI.FOOD_TYPE DESC;
