WITH SCORE AS (
    SELECT REST_ID, AVG(REVIEW_SCORE) AS AVG_SCORE
    FROM REST_REVIEW
    WHERE REST_ID IN (
        SELECT REST_ID
        FROM REST_INFO
        WHERE ADDRESS LIKE '서울%'
    )
    GROUP BY REST_ID
)
SELECT 
    RI.REST_ID, 
    REST_NAME, 
    FOOD_TYPE, 
    FAVORITES, 
    ADDRESS,
    ROUND(AVG_SCORE, 2) AS SCORE
FROM REST_INFO RI
JOIN SCORE SC
ON RI.REST_ID = SC.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;


