WITH TOTAL_FISH_COUNT AS (
    SELECT FISH_TYPE
            , COUNT(FISH_TYPE) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT FISH_COUNT, FISH_NAME
FROM TOTAL_FISH_COUNT TC
LEFT JOIN FISH_NAME_INFO FI
ON TC.FISH_TYPE = FI.FISH_TYPE
ORDER BY FISH_COUNT DESC;