-- 코드를 입력하세요
WITH USER_N AS (
SELECT  *
  FROM  USER_INFO AS U
 WHERE  YEAR(JOINED) = 2021
)
#2021년 가입한 회원

SELECT  YEAR(O.SALES_DATE) AS YEAR
        ,MONTH(O.SALES_DATE) AS MONTH
        ,COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS #구매이력있는 회원
        ,ROUND(
        COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) FROM USER_N), 1) AS PUCHASED_RATIO
  FROM  ONLINE_SALE AS O
  JOIN  USER_N AS UN
    ON  O.USER_ID = UN.USER_ID
 WHERE  O.USER_ID IN (SELECT USER_ID FROM USER_N)
 GROUP
    BY  YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
 ORDER
    BY  YEAR, MONTH