WITH RECURSIVE ECOLI_TREE AS (
    -- 최초 세대의 대장균 개체들을 찾기
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 재귀적으로 다음 세대의 개체들을 찾기
    SELECT ed.ID, ed.PARENT_ID, et.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA ed
    INNER JOIN ECOLI_TREE et ON ed.PARENT_ID = et.ID
)

SELECT * 
FROM ECOLI_TREE;

# -- 각 세대별로 자식이 없는 개체 수 계산
# SELECT COUNT(*) AS COUNT, GENERATION
# FROM ECOLI_TREE
# WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
# GROUP BY GENERATION
# ORDER BY GENERATION;