# SELECT 
#     QUARTER
#     , COUNT(QUARTER) AS ECOLI_COUNT
# FROM (
#     SELECT
#         (CASE 
#             WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
#             WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
#             WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
#             ELSE '4Q'
#          END) AS QUARTER
#     FROM ECOLI_DATA
# ) QT
# GROUP BY QUARTER
# ORDER BY QUARTER ASC;

SELECT
    CONCAT(FLOOR((MONTH(DIFFERENTIATION_DATE)-1)/3 + 1), 'Q')       AS QUARTER
    , COUNT(ID)                                                     AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER