SELECT
    H.HISTORY_ID,
    FLOOR(
        CASE
            -- 대여 기간이 7일 미만일 경우 할인 없음
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
            -- 대여 기간이 7일 이상 30일 미만인 경우 5% 할인 적용
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - (DP.DISCOUNT_RATE / 100))
            -- 대여 기간이 30일 이상 90일 미만인 경우 7% 할인 적용
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - (DP.DISCOUNT_RATE / 100))
            -- 대여 기간이 90일 이상인 경우 10% 할인 적용
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - (DP.DISCOUNT_RATE / 100))
        END
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN
    CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON C.CAR_TYPE = DP.CAR_TYPE
        AND (
            (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 AND DP.DURATION_TYPE = '7일 이상')
            OR (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 AND DP.DURATION_TYPE = '30일 이상')
            OR (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 AND DP.DURATION_TYPE = '90일 이상')
        )
WHERE
    C.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC, H.HISTORY_ID DESC;
