-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF fh
JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) SUM_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) july
USING (FLAVOR)
ORDER BY (fh.TOTAL_ORDER + july.SUM_ORDER) desc
LIMIT 3;