SELECT
    USER_ID,
    NICKNAME,
    SUM(IF(STATUS = 'DONE', PRICE, 0)) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;