-- 코드를 입력하세요
SELECT mp.MEMBER_NAME, best.REVIEW_TEXT, date_format(best.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE mp
JOIN (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) desc
        LIMIT 1
    )
) best
USING (MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT;

