WITH ID AS (
    SELECT ITEM_ID AS ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IN (
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
    )
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
JOIN ID
ON ITEM_ID = ID
ORDER BY ITEM_ID DESC;