SELECT 
    CH.ID
    , CH.GENOTYPE
    , PA.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CH
    , ECOLI_DATA PA
WHERE PA.ID = CH.PARENT_ID
     AND CH.GENOTYPE & PA.GENOTYPE = PA.GENOTYPE
ORDER BY ID ASC;