SELECT YEAR, (ms.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA ed
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE ,YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) AS ms 
ON YEAR(ed.DIFFERENTIATION_DATE) = ms.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;