WITH MAX_FISH AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT 
    ID,
    FISH_NAME,
    LENGTH
FROM FISH_INFO FI
JOIN MAX_FISH
USING (FISH_TYPE)
JOIN FISH_NAME_INFO
USING (FISH_TYPE)
WHERE LENGTH = MAX_LENGTH
ORDER BY ID;