WITH TOTAL_SCORE AS (
    SELECT EMP_NO
            , SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT SUM_SCORE AS SCORE
    , HE.EMP_NO
    , EMP_NAME
    , POSITION
    , EMAIL
    FROM HR_EMPLOYEES HE, TOTAL_SCORE TS
    WHERE HE.EMP_NO = TS.EMP_NO
    AND SUM_SCORE = (
                        SELECT MAX(SUM_SCORE) 
                        FROM TOTAL_SCORE);