WITH MAX_PRICE_BY_CATEGORY AS (
    SELECT CATEGORY
        , MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT FD.CATEGORY
    , MAX_PRICE
    , PRODUCT_NAME
FROM FOOD_PRODUCT FD
JOIN MAX_PRICE_BY_CATEGORY MP
ON FD.CATEGORY = MP.CATEGORY
    AND FD.PRICE = MP.MAX_PRICE
ORDER BY MAX_PRICE DESC;